MathaCapital/Models/WinResults.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using MathaCapital.Areas.Identity.Data;

namespace MathaCapital.Models
{
    public class WinResults
    {
        public int ID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime FwdDate { get; set; }

        [Display(Name = "Bank Name")]
        public string BankName { get; set; }
        public AuctionBid AuctionBid { get; set; }
        public int AuctionBidID { get; set; }

        [Display(Name = "Forward Rate")]
        public double FwdRate { get; set; }

        [Display(Name = "Amount Bid")]
        [Column(TypeName = "decimal(18,2)")]
        [DisplayFormat(DataFormatString = "{0:0,0.00}")]
        public decimal AmountBid { get; set; }

        [Display(Name = "Coupon Amount")]
        [Column(TypeName = "decimal(18,2)")]
        [DisplayFormat(DataFormatString = "{0:0,0.00}")]
        public decimal CouponAmount { get; set; }

        [Display(Name = "Win Amount")]
        [Column(TypeName = "decimal(18,2)")]
        [DisplayFormat(DataFormatString = "{0:0,0.00}")]
        public decimal WinAmount { get; set; }

        public string BatchRef { get; set; }

        public string UserName { get; set; }
        public MathaCapitalUser User { get; set; }
    }

}

MathaCapital/Controllers/WinResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MathaCapital.Data;
using MathaCapital.Models;
using System.Text;
using OfficeOpenXml;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace MathaCapital.Controllers
{
    public class WinResultsController : Controller
    {
        private readonly AuctionContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;
        public WinResultsController(AuctionContext context, IHostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
        }

        // Export Wins to Excel
        public IActionResult ExportWinData(string bidBatch)
        {
            var sb = new StringBuilder();
            var data = from s in _context.WinResults
                       where s.BatchRef == bidBatch
                       select new
                       {
                           s.AuctionBidID,
                           s.FwdDate,
                           s.BankName,
                           s.FwdRate,
                           s.AmountBid,
                           s.WinAmount,
                           s.CouponAmount,
                           s.BatchRef
                       };
            var list = data.ToList();
            byte[] fileContents;
            var memory = new MemoryStream();
            using (ExcelPackage package = new ExcelPackage())
            {
                ExcelWorksheet wSheet = package.Workbook.Worksheets.Add("Win");
                int totalRows = list.Count();

                wSheet.Cells[1, 1].Value = "Auction ID";
                wSheet.Cells[1, 2].Value = "Fwd Date";
                wSheet.Cells[1, 3].Value = "Bank Name";
                wSheet.Cells[1, 4].Value = "Fwd Rate";
                wSheet.Cells[1, 5].Value = "Amount Bid";
                wSheet.Cells[1, 6].Value = "Amount Won";
                wSheet.Cells[1, 7].Value = "Coupon Amount";
                wSheet.Cells[1, 8].Value = "Batch Reference";
                wSheet.Cells[1, 1].Style.Font.Bold = true;
                wSheet.Cells[1, 2].Style.Font.Bold = true;
                wSheet.Cells[1, 3].Style.Font.Bold = true;
                wSheet.Cells[1, 4].Style.Font.Bold = true;
                wSheet.Cells[1, 5].Style.Font.Bold = true;
                wSheet.Cells[1, 6].Style.Font.Bold = true;
                wSheet.Cells[1, 7].Style.Font.Bold = true;
                wSheet.Cells[1, 8].Style.Font.Bold = true;
                int i = 0;
                for (int row = 2; row < totalRows + 1; row++)
                {
                    wSheet.Cells[row, 1].Value = list[i].AuctionBidID;
                    wSheet.Cells[row, 2].Value = list[i].FwdDate;
                    wSheet.Cells[row, 3].Value = list[i].BankName;
                    wSheet.Cells[row, 4].Value = list[i].FwdRate;
                    wSheet.Cells[row, 5].Value = list[i].AmountBid;
                    wSheet.Cells[row, 6].Value = list[i].WinAmount;
                    wSheet.Cells[row, 7].Value = list[i].CouponAmount;
                    wSheet.Cells[row, 8].Value = list[i].BatchRef;
                    i++;
                }
                fileContents = package.GetAsByteArray();
            }
            if (fileContents == null || fileContents.Length == 0)
            {
                return NotFound();
            }
            return File(
                fileContents: fileContents,
                contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                fileDownloadName: "ExportWins.xlsx");
        }


        // GET: WinResults
        public async Task<IActionResult> Index(string bidBatch, string sortOrder, string bankName, string fwdDate)
        {
            IQueryable<string> batchQuery = from b in _context.AuctionBids
                                            orderby b.BatchRef
                                            select b.BatchRef;
            IQueryable<string> bankQuery = from d in _context.WinResults
                                           orderby d.BankName
                                           select d.BankName;

            var wins = from m in _context.WinResults
                       select m;

            if (!string.IsNullOrEmpty(bidBatch))
            {
                wins = wins.Where(x => x.BatchRef == bidBatch);
            }

            if (!string.IsNullOrEmpty(bankName))
            {
                wins = wins.Where(y => y.BankName == bankName);
            }

            if (!string.IsNullOrEmpty(fwdDate))
            {
                wins = wins.Where(z => z.FwdDate == Convert.ToDateTime(fwdDate));
            }

            switch (sortOrder)
            {
                case "sortByBank":
                    wins = wins.OrderBy(s => s.BankName).ThenBy(s => s.FwdDate);
                    break;

                case "sortByDate":
                    wins = wins.OrderBy(s => s.FwdDate).ThenByDescending(s => s.FwdRate);
                    break;
            }

            var bidVM = new BidBatchViewModel();
            bidVM.banks = new SelectList(await bankQuery.Distinct().ToListAsync());
            bidVM.batches = new SelectList(await batchQuery.Distinct().ToListAsync());
            bidVM.wins = await wins.ToListAsync();
            return View(bidVM);
        }



        // GET: WinResults/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var winResults = await _context.WinResults
                .Include(w => w.AuctionBid)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (winResults == null)
            {
                return NotFound();
            }

            return View(winResults);
        }

        // GET: WinResults/Create
        public IActionResult Create()
        {
            ViewData["AuctionBidID"] = new SelectList(_context.AuctionBids, "ID", "ID");
            return View();
        }

        // POST: WinResults/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FwdDate,BankName,AuctionBidID,FwdRate,AmountBid,CouponAmount,WinAmount")] WinResults winResults)
        {
            if (ModelState.IsValid)
            {
                _context.Add(winResults);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuctionBidID"] = new SelectList(_context.AuctionBids, "ID", "ID", winResults.AuctionBidID);
            return View(winResults);
        }

        // GET: WinResults/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var winResults = await _context.WinResults.SingleOrDefaultAsync(m => m.ID == id);
            if (winResults == null)
            {
                return NotFound();
            }
            ViewData["AuctionBidID"] = new SelectList(_context.AuctionBids, "ID", "ID", winResults.AuctionBidID);
            return View(winResults);
        }

        // POST: WinResults/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FwdDate,BankName,AuctionBidID,FwdRate,AmountBid,CouponAmount,WinAmount")] WinResults winResults)
        {
            if (id != winResults.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(winResults);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WinResultsExists(winResults.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuctionBidID"] = new SelectList(_context.AuctionBids, "ID", "ID", winResults.AuctionBidID);
            return View(winResults);
        }

        // GET: WinResults/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var winResults = await _context.WinResults
                .Include(w => w.AuctionBid)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (winResults == null)
            {
                return NotFound();
            }

            return View(winResults);
        }

        // POST: WinResults/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var winResults = await _context.WinResults.SingleOrDefaultAsync(m => m.ID == id);
            _context.WinResults.Remove(winResults);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WinResultsExists(int id)
        {

MathaCapital/Views/WinResults/Create.cshtml
@model MathaCapital.Models.WinResults

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>WinResults</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FwdDate" class="control-label"></label>
                <input asp-for="FwdDate" class="form-control" />
                <span asp-validation-for="FwdDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <input asp-for="BankName" class="form-control" />
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuctionBidID" class="control-label"></label>
                <select asp-for="AuctionBidID" class ="form-control" asp-items="ViewBag.AuctionBidID"></select>
            </div>
            <div class="form-group">
                <label asp-for="FwdRate" class="control-label"></label>
                <input asp-for="FwdRate" class="form-control" />
                <span asp-validation-for="FwdRate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmountBid" class="control-label"></label>
                <input asp-for="AmountBid" class="form-control" />
                <span asp-validation-for="AmountBid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CouponAmount" class="control-label"></label>
                <input asp-for="CouponAmount" class="form-control" />
                <span asp-validation-for="CouponAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WinAmount" class="control-label"></label>
                <input asp-for="WinAmount" class="form-control" />
                <span asp-validation-for="WinAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BatchRef" class="control-label"></label>
                <input asp-for="BatchRef" class="form-control" />
                <span asp-validation-for="BatchRef" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MathaCapital/Views/WinResults/Delete.cshtml
@model MathaCapital.Models.WinResults

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WinResults</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FwdDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FwdDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BankName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BankName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FwdRate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FwdRate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AmountBid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AmountBid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CouponAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CouponAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.WinAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WinAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BatchRef)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BatchRef)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AuctionBid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AuctionBid.ID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MathaCapital/Views/WinResults/Details.cshtml
@model MathaCapital.Models.WinResults

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>WinResults</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FwdDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FwdDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BankName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BankName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FwdRate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FwdRate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AmountBid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AmountBid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CouponAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CouponAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.WinAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.WinAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BatchRef)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BatchRef)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AuctionBid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AuctionBid.ID)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MathaCapital/Views/WinResults/Edit.cshtml
@model MathaCapital.Models.WinResults

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>WinResults</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FwdDate" class="control-label"></label>
                <input asp-for="FwdDate" class="form-control" />
                <span asp-validation-for="FwdDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <input asp-for="BankName" class="form-control" />
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuctionBidID" class="control-label"></label>
                <select asp-for="AuctionBidID" class="form-control" asp-items="ViewBag.AuctionBidID"></select>
                <span asp-validation-for="AuctionBidID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FwdRate" class="control-label"></label>
                <input asp-for="FwdRate" class="form-control" />
                <span asp-validation-for="FwdRate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmountBid" class="control-label"></label>
                <input asp-for="AmountBid" class="form-control" />
                <span asp-validation-for="AmountBid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CouponAmount" class="control-label"></label>
                <input asp-for="CouponAmount" class="form-control" />
                <span asp-validation-for="CouponAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WinAmount" class="control-label"></label>
                <input asp-for="WinAmount" class="form-control" />
                <span asp-validation-for="WinAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BatchRef" class="control-label"></label>
                <input asp-for="BatchRef" class="form-control" />
                <span asp-validation-for="BatchRef" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MathaCapital/Views/WinResults/Index.cshtml
@model MathaCapital.Models.BidBatchViewModel
@{
    ViewData["Title"] = "Win Results";
}

<h2>Win Results</h2>
<div class="container">

    <div class="form-group">
        <form asp-controller="WinResults" asp-action="Index" class="form-inline">
            <label for="batch" class="form-inline">Batch Reference:</label>
            <select class="form-control" asp-for="bidBatch" asp-items="Model.batches">
                <option value="">All</option>
            </select>
            &nbsp;
            <label class="form-inline">  Bank Name:</label>
            <select class="form-control" asp-for="bankName" asp-items="Model.banks">
                <option value="">All</option>
            </select>
            &nbsp;
            <label class="form-inline">  Date</label>
            <input type="date" name="fwdDate" max="3000-12-31"
                   min="2010-01-01" class="form-control">
            <button type="submit" class="btn btn-primary">Search</button>&nbsp;
            <button type="submit" asp-action="ExportWinData" class="btn btn-default" >Export to Excel</button>
        </form>
    </div>
</div>

<table class="table table-striped">
    <thead>
        <tr>
            <th class="col-lg-2">
                @Html.DisplayNameFor(model => model.wins[0].FwdDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.wins[0].BankName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.wins[0].FwdRate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.wins[0].AmountBid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.wins[0].CouponAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.wins[0].WinAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.wins[0].BatchRef)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.wins[0].AuctionBidID)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.wins)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FwdDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BankName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FwdRate)
                </td>
                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.AmountBid)
                </td>
                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.CouponAmount)
                </td>
                <td class="text-right text">
                    <strong>
                        @Html.DisplayFor(modelItem => item.WinAmount)
                    </strong>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BatchRef)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AuctionBidID)
                </td>
            </tr>
        }

    </tbody>
</table>