MathaCapital/Controllers/ImportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using MathaCapital.Areas.Identity.Data;
using MathaCapital.Data;
using MathaCapital.Models;


namespace MathaRx.Controllers
{
    [Authorize]
    public class ImportController : Controller
    {
        private readonly AuctionContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly UserManager<MathaCapitalUser> _userManager;

        public int lineCount;
        public string lineMessage;

        public ImportController(IHostingEnvironment hostingEnvironment, AuctionContext db, UserManager<MathaCapitalUser> userManager)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = db;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        protected void ImportExcel(object sender, EventArgs e)
        {
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> UploadExcel(IFormFile file, string batchPre)
        {
            if (file == null || file.Length < 0)
            {
                return Content("file not selected.");
            }
            await UploadFile(file);

            await ImportDataAsync(batchPre);
            ViewData["Error"] = lineMessage;
            ViewData["Message"] = lineCount + " Lines have been successfuly imported into the database.";
            return View();
        }


        private async Task<bool> ImportDataAsync(string batchPre)
        {
            bool result = false;
            string folderName = "import";
            string rootFolder = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(rootFolder, folderName);
            string[] file = Directory.GetFiles(newPath, "*.xlsx");
            string fullPath = Path.Combine(newPath, file[0]);
            FileInfo fileInfo = new FileInfo(fullPath);
            string batchRef = DateTime.Now.ToString("ddMMyyyy-HHmm");

            try
            {
                using (ExcelPackage package = new ExcelPackage(fileInfo))
                {
                    ExcelWorksheet workSheet = package.Workbook.Worksheets[1];
                    int totalRows = workSheet.Dimension.Rows;
                    List<AuctionBid> auctionBids = new List<AuctionBid>();
                    lineCount = 0;
                    for (int i = 2; i <= totalRows; i++)
                    {
                        try
                        {
                            string fDate = workSheet.Cells[i, 1].Value.ToString();
                            double date = double.Parse(fDate);
                            auctionBids.Add(new AuctionBid
                            {
                                BankName = workSheet.Cells[i, 5].Value.ToString(),
                                FwdDate = DateTime.FromOADate(date),
                                FwdRate = Math.Round(double.Parse(workSheet.Cells[i, 3].Value.ToString()), 6),
                                AmountBid = decimal.Parse(workSheet.Cells[i, 4].Value.ToString()),
                                CouponAmount = decimal.Parse(workSheet.Cells[i, 2].Value.ToString()),
                                Pips = decimal.Parse(workSheet.Cells[i, 6].Value.ToString()),
                                BatchRef = batchRef,
                                UserName = _userManager.GetUserName(HttpContext.User)
                            });
                            lineCount++;
                            DeleteFiles();
                        }
                        catch (Exception e)
                        {
                            lineMessage = e.Message.ToString();
                        }
                    }
                    await _context.AuctionBids.AddRangeAsync(auctionBids);
                    _context.SaveChanges();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("{0} First exception caught.", ex.Message);
            }
            return result;
        }

        public async Task<IActionResult> UploadFile(IFormFile file)
        {
            if (file == null || file.Length < 0)
            {
                return Content("file not selected.");
            }
            string fileName = @"importedfile.xlsx";
            string folderName = "import";
            string rootFolder = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(rootFolder, folderName);
            string path = Path.Combine(newPath, fileName);
            using (var stream = new FileStream(path, FileMode.Create))
            {
               await file.CopyToAsync(stream);
            }
            return Ok();
        }

        public ActionResult DeleteFiles()
        {
            string folderName = "import";
            string rootFolder = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(rootFolder, folderName);
            DirectoryInfo d = new DirectoryInfo(newPath);
            FileInfo[] files = d.GetFiles("*.xlsx");
            foreach (FileInfo file in files)
            {
                file.Delete();
            }
            return Ok();
        }
    }
}

MathaCapital/Views/Import/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="container-fluid">

    <h2>Import Bids via Excel </h2>
    <p>This page allows you to upload a set of bids into the database from an excel sheet. Only *.xlsx files will be accepted.</p>

</div>

<div class="container">
    <script type="text/javascript">
        function validate(fld) {
            if (!/(\.xlsx)$/i.test(fld.value)) {
                alert("Invalide file type!");
                fld.form.reset();
                fld.focus();
                return false;
            }
            return true;
        }
    </script>
    <div class="col-md-6">
        <form asp-controller="Import" asp-action="UploadExcel" method="post" enctype="multipart/form-data" onsubmit="validate(this.file)">
            <div class="form-group">
                <input type="file" name="file" class="form-control" onchange="return validate(this);" /><br />
                <input class="btn btn-primary" type="submit" value="Import" />
            </div>
        </form>
    </div>

    <p class="alert-success">@ViewData["Message"]</p>


</div>

MathaCapital/Views/Import/UploadExcel.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="container-fluid">

    <h2>Imported Bids via Excel </h2>

</div>

<div class="container">
    <a asp-action="Index">Back to Upload Page</a>
    <p class="alert-success">@ViewData["Message"]</p>
    @*<p class="alert-danger">@ViewData["Error"]</p>*@
</div>