MathaCapital/Controllers/BidsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MathaCapital.Data;
using MathaCapital.Models;
using Microsoft.AspNetCore.Hosting;
using System.Collections.Generic;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using MoreLinq;
using System.Data.SqlClient;
using MathaCapital.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;

namespace MathaCapital.Controllers
{
    //[Authorize]
    public class BidsController : Controller
    {
        private readonly AuctionContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly UserManager<MathaCapitalUser> _userManager;
        private readonly string _connString;

        public BidsController(IHostingEnvironment hostingEnvironment, AuctionContext db, UserManager<MathaCapitalUser> userManager)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = db;
            _userManager = userManager;
            _connString = db.Database.GetDbConnection().ConnectionString;
        }


        public async Task<IActionResult> DeleteBatch(string bidBatch)
        {
            var relWins = _context.WinResults.Where(x => x.BatchRef == bidBatch);
            if (relWins.Count() == 0)
            {
                var deleteBatch = _context.AuctionBids.Where(x => x.BatchRef == bidBatch);
                foreach (var item in deleteBatch)
                {
                    _context.AuctionBids.Remove(item);
                }
                await _context.SaveChangesAsync();
                ViewData["Message"] = bidBatch + " has been deleted by " + _userManager.GetUserName(HttpContext.User) + ".";
            }
            else
            {
                ViewData["Message"] = bidBatch + " cannot be deleted because there are wins associated with it.";
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PerAuctionRun(BankPercViewModel data)
        {
            var testTotal = new Double();
            foreach (var item in data.perbank)
            {
                testTotal += Convert.ToDouble(item.Percent);
            }
            
            //Get a list of dates in this Batch
            List<DateTime> res = (from a in _context.AuctionBids
                                  where a.BatchRef.ToString() == data.bidBatch
                                  orderby a.FwdDate
                                  select a.FwdDate).Distinct().ToList();
           
            // Delete wins before running auction again
            _context.WinResults.Where(w => w.BatchRef == data.bidBatch).ToList().ForEach(p => _context.WinResults.Remove(p));
            await _context.SaveChangesAsync();

            if (testTotal == 100)
            {
                foreach (var date in res)
                {
                    IQueryable<AuctionBid> bids = from j in _context.AuctionBids
                                                     where j.FwdDate == date
                                                     select j;
                    DataTable dTable = new DataTable();
                    dTable.Columns.Add("ID", typeof(int));
                    dTable.Columns.Add("FwdDate", typeof(DateTime));
                    dTable.Columns.Add("CouponAmount", typeof(decimal));
                    dTable.Columns.Add("BankName", typeof(string));
                    dTable.Columns.Add("AmountBid", typeof(decimal));
                    dTable.Columns.Add("FwdRate", typeof(double));
                    dTable.Columns.Add("awarded_amount", typeof(decimal));
                    dTable.Columns.Add("BatchRef", typeof(string));
                    dTable.Columns.Add("UserName", typeof(string));

                    foreach (var row in bids)
                    {
                        Decimal ratio = new Decimal();
                        ratio = Convert.ToDecimal(data.perbank.Where(x => x.BankName == row.BankName).Select(x => x.Percent).First());
                        DataRow dRow = dTable.NewRow();
                        dRow[0] = row.ID;
                        dRow[1] = row.FwdDate;
                        dRow[2] = row.CouponAmount;
                        dRow[3] = row.BankName;
                        dRow[4] = row.AmountBid;
                        dRow[5] = row.FwdRate;
                        dRow[6] = row.CouponAmount * ratio/100;
                        dRow[7] = row.BatchRef;
                        dRow[8] = row.UserName;

                        dTable.Rows.Add(dRow);
                    }

                    // Convert Date wins to object and write to entity
                    foreach (DataRow row in dTable.Rows)
                    {
                        WinResults convertedObject = ConvertRowToWinResult(row);
                        if (convertedObject.WinAmount != 0)
                        {
                            _context.WinResults.Add(convertedObject);
                        }
                    }
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction("Index", "WinResults");
            }
            else
            {
                ViewData["Message"] = "The total of the percentages is more or less than 100.";
                return View();
            }
        }

        // Run Auction for a Batch
        public async Task<IActionResult> RunAuction(string bidBatch, string auctionType)
        {

            //Get a list of dates in this Batch
            List<DateTime> res = (from a in _context.AuctionBids
                                  where a.BatchRef.ToString() == bidBatch
                                  orderby a.FwdDate
                                  select a.FwdDate).Distinct().ToList();

            // Delete wins before running auction again
            _context.WinResults.Where(x => x.BatchRef == bidBatch).ForEach(p => _context.WinResults.Remove(p));

            if (auctionType == "bestrate")
            {
                foreach (var date in res)
                {
                    // Direct SQL to pick winners for a date
                    string sqlQry = "select ID, FwdDate, CouponAmount, BankName, AmountBid, FwdRate, BatchRef, case when remainder < 0 then remainder_1 else " +
                        "AmountBid end awarded_amount from (select *, LAG(remainder) over(order by FwdRate desc) remainder_1 " +
                        "from (select ID, FwdDate, CouponAmount, BankName, AmountBid, FwdRate, BatchRef, SUM(AmountBid) over (order by FwdRate desc) rtotal, " +
                        "CouponAmount - SUM(AmountBid) over (order by FwdRate desc) as remainder from AuctionBid where FwdDate=@fwdDate and BatchRef=@batchRef) tb) a where case when remainder < 0 then remainder_1 else AmountBid end >= 0";
                    using (SqlConnection conn = new SqlConnection(_connString))
                    {
                        using (SqlCommand comm = new SqlCommand(null, conn))
                        {
                            conn.Open();
                            comm.CommandText = sqlQry;
                            SqlParameter param1 = comm.Parameters.Add("@fwdDate", SqlDbType.DateTime2, 8);
                            SqlParameter param2 = comm.Parameters.Add("@batchRef", SqlDbType.NVarChar, 100);

                            param1.Value = date;
                            param2.Value = bidBatch;

                            comm.Prepare();
                            SqlDataReader reader = comm.ExecuteReader();
                            DataTable dt = new DataTable();

                            dt.Load(reader);
                            conn.Close();

                            // Convert Date wins to object and write to entity
                            foreach (DataRow row in dt.Rows)
                            {
                                WinResults convertedObject = ConvertRowToWinResult(row);
                                if (convertedObject.WinAmount != 0)
                                {
                                    _context.WinResults.Add(convertedObject);
                                }
                            }
                            await _context.SaveChangesAsync();
                        }
                    }
                }
            }
            else if (auctionType == "waverage")
            {
                foreach (var date in res)
                {
                    IQueryable<AuctionBid> bids = from j in _context.AuctionBids
                                                     where j.FwdDate == date
                                                     select j;
                    var totalAmt = bids.Select(x => x.AmountBid).Sum();
                    var bidArray = bids.ToArray();

                    DataTable dTable = new DataTable();
                    dTable.Columns.Add("ID", typeof(int));
                    dTable.Columns.Add("FwdDate", typeof(DateTime));
                    dTable.Columns.Add("CouponAmount", typeof(decimal));
                    dTable.Columns.Add("BankName", typeof(string));
                    dTable.Columns.Add("AmountBid", typeof(decimal));
                    dTable.Columns.Add("FwdRate", typeof(double));
                    dTable.Columns.Add("awarded_amount", typeof(decimal));
                    dTable.Columns.Add("BatchRef", typeof(string));

                    foreach (var row in bids)
                    {
                        DataRow dRow = dTable.NewRow();
                        dRow[0] = row.ID;
                        dRow[1] = row.FwdDate;
                        dRow[2] = row.CouponAmount;
                        dRow[3] = row.BankName;
                        dRow[4] = row.AmountBid;
                        dRow[5] = row.FwdRate;

MathaCapital/Views/Bids/Create.cshtml
@model MathaCapital.Models.AuctionBid

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>AuctionBid</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FwdDate" class="control-label"></label>
                <input asp-for="FwdDate" class="form-control" />
                <span asp-validation-for="FwdDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <input asp-for="BankName" class="form-control" />
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FwdRate" class="control-label"></label>
                <input asp-for="FwdRate" class="form-control" />
                <span asp-validation-for="FwdRate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmountBid" class="control-label"></label>
                <input asp-for="AmountBid" class="form-control" />
                <span asp-validation-for="AmountBid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CouponAmount" class="control-label"></label>
                <input asp-for="CouponAmount" class="form-control" />
                <span asp-validation-for="CouponAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pips" class="control-label"></label>
                <input asp-for="Pips" class="form-control" />
                <span asp-validation-for="Pips" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BatchRef" class="control-label"></label>
                <input asp-for="BatchRef" class="form-control" />
                <span asp-validation-for="BatchRef" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MathaCapital/Views/Bids/Delete.cshtml
@model MathaCapital.Models.AuctionBid

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AuctionBid</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FwdDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FwdDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BankName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BankName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FwdRate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FwdRate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AmountBid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AmountBid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CouponAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CouponAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pips)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pips)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BatchRef)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BatchRef)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MathaCapital/Views/Bids/DeleteBatch.cshtml
@{
    ViewData["Title"] = "DeleteBatch";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h4>@ViewData["Message"]</h4>
    <a asp-action="Index">Back to bids.</a>
</div>

MathaCapital/Views/Bids/Details.cshtml
@model MathaCapital.Models.AuctionBid

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>AuctionBid</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FwdDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FwdDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BankName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BankName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FwdRate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FwdRate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AmountBid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AmountBid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CouponAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CouponAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pips)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pips)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BatchRef)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BatchRef)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MathaCapital/Views/Bids/Edit.cshtml
@model MathaCapital.Models.AuctionBid

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>AuctionBid</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FwdDate" class="control-label"></label>
                <input asp-for="FwdDate" class="form-control" />
                <span asp-validation-for="FwdDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BankName" class="control-label"></label>
                <input asp-for="BankName" class="form-control" />
                <span asp-validation-for="BankName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FwdRate" class="control-label"></label>
                <input asp-for="FwdRate" class="form-control" />
                <span asp-validation-for="FwdRate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AmountBid" class="control-label"></label>
                <input asp-for="AmountBid" class="form-control" />
                <span asp-validation-for="AmountBid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CouponAmount" class="control-label"></label>
                <input asp-for="CouponAmount" class="form-control" />
                <span asp-validation-for="CouponAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pips" class="control-label"></label>
                <input asp-for="Pips" class="form-control" />
                <span asp-validation-for="Pips" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BatchRef" class="control-label"></label>
                <input asp-for="BatchRef" class="form-control" />
                <span asp-validation-for="BatchRef" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MathaCapital/Views/Bids/Index.cshtml
@model MathaCapital.Models.BidBatchViewModel

@{
    ViewData["Title"] = "Auction Bids";
}

<div class="container">
    <h2>Auction Bids</h2>

    <p>
        <a asp-action="Create" class="btn btn-primary">Create New</a>
    </p>
    <div class="container">
        <form asp-controller="Bids" asp-action="Index" class="form-inline">
            <div class="form-inline">
                <label for="batch" class="form-inline">Batch Ref:</label>
                <select class="form-control" asp-for="bidBatch" asp-items="Model.batches">
                    <option value="">All</option>
                </select>
                <label for="date" class="form-inline">&nbsp;Date:</label>
                <input type="date" name="fwdDate" max="3000-12-31"
                       min="2010-01-01" class="form-control">
                <label for="search" class="form-inline">&nbsp;Bank:</label>
                <input type="text" name="searchString" class="form-control" id="search" placeholder="Type Bank Name Here.." />
                &nbsp;
                <button type="submit" class="btn btn-primary">Search</button>
                <select class="form-control" asp-for="auctionType">
                    <option value="bestrate">Best Rate</option>
                    <option value="waverage">Weighted Averages</option>
                    <option value="percentage">Percentages</option>
                </select>
                <button asp-action="RunAuction" class="btn">Run Auction</button>
                <button asp-action="DeleteBatch" class="btn btn-danger" Onclick="ConfirmDelete()">Delete Batch</button>
            </div>
            <script type="text/javascript">
                function ConfirmDelete() {
                    var x = confirm("Are you sure you want to delete this batch?");
                    if (x) {
                        return true;
                    }
                    else {
                        return false;
                    }
                }
            </script>
        </form>
    </div>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.bids[0].FwdDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bids[0].BankName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bids[0].FwdRate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bids[0].AmountBid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bids[0].CouponAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bids[0].Pips)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bids[0].BatchRef)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.bids)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FwdDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BankName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FwdRate)
                </td>
                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.AmountBid)
                </td>
                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.CouponAmount)
                </td>
                <td class="text-right">
                    @Html.DisplayFor(modelItem => item.Pips)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BatchRef)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MathaCapital/Views/Bids/PerAuctionRun.cshtml
@{
    ViewData["Title"] = "PerAuctionRun";
}

<h4 class="alert-danger">@ViewData["Message"]</h4>


<div>
        <a asp-action="Index">Back to List</a>
</div>

MathaCapital/Views/Bids/RunAuction.cshtml
@model MathaCapital.Models.BankPercViewModel

@{
    ViewData["Title"] = "RunAuction";
}

<h2>RunAuction</h2>

<h4>
    Banks for Auction with Batch Reference "@Model.bidBatch"
</h4>
<hr />
<div class="row">
    <div class="col-md-4">


        @using (Html.BeginForm("PerAuctionRun", "Bids", FormMethod.Post))
        {
            <table class="table-striped">
                <thead>
                    <tr>
                        <th>
                            Bank Name
                        </th>
                        <th>
                            Percentage
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int i = 0;
                        @foreach (var item in Model.perbank.ToList())
                        {
                            <tr>
                                @Html.HiddenFor(u => u.perbank[i].ID)
                                <td>
                                    @Html.DisplayFor(modelItem => modelItem.perbank[i].BankName)
                                    @Html.HiddenFor(m => m.perbank[i].BankName)
                                </td>
                                <td>
                                    @Html.TextBoxFor(modelItem => modelItem.perbank[i].Percent)
                                </td>
                            </tr>
                            i++;
                        }
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td>Total </td>
                        <td><span id="sum">0</span></td>
                    </tr>
                </tfoot>
            </table><br />
            <div class="form-group">
                @Html.HiddenFor(m => m.bidBatch)
                <input type="submit" value="Run Auction" class="btn btn-primary" />
            </div>
        }
    </div>
    <script type="text/javascript">


    </script>
</div>

<div>
        <a asp-action="Index">Back to did list</a>
    </div>